services:
  s3:
    image: minio/minio:RELEASE.2024-08-17T01-24-54Z
    container_name: dockerbasics_compose_s3
    environment:
      MINIO_ACCESS_KEY: user
      MINIO_SECRET_KEY: password
    volumes:
      - s3_volume:/data
    networks: &default-networks
      - common_net
    ports:
      - 11112:9001
    command: server /data --console-address ":9001"
    restart: always
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 2


  db:
    image: postgres:16.4-alpine
    container_name: dockerbasics_compose_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - db_volume:/var/lib/postgresql/data
    networks: *default-networks
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "psql -U user -d db -c 'SELECT 1'"]
      interval: 5s
      timeout: 5s
      retries: 3

  app:
    image: dockerbasics_compose_app:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: dockerbasics_compose_app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: db
      S3_HOST: s3
      S3_PORT: 9000
      S3_ACCESS_KEY: user
      S3_SECRET_KEY: password
    networks: *default-networks
    ports:
      - 11111:80
    depends_on:
      db:
        condition: service_healthy
      s3:
        condition: service_healthy

networks:
  common_net:
    name: dockerbasics_compose_net

volumes:
  db_volume:
    name: dockerbasics_compose_db_volume
  s3_volume:
    name: dockerbasics_compose_s3_volume
